spring.application.name=Colombianita

# 1. Credenciales de tu Oracle Database en la Nube (26ai)
# REGLA: Reemplaza la ruta por la ubicación real donde guardaste el .zip en tu compu
spring.datasource.url=jdbc:oracle:thin:@pizzeriacolombianita_high?TNS_ADMIN=C:/Users/kevin//Documents/Wallet_PizzeriaColombianita
spring.datasource.username=ADMIN
spring.datasource.password=Alejaquin2711*
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# 2. Configuración de Hibernate (El motor de JPA)
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.show-sql=true

# ¡VITAL! Evita que Java borre o modifique tus tablas de Oracle
spring.jpa.hibernate.ddl-auto=none

# Puerto donde correrá el servidor backend
server.port=8080